// Generated by CoffeeScript 1.12.7
(function() {
  var App, DOLLAR_R, HOUR_R, YEN_R, get_num, on_error, transform_card;

  on_error = function(error) {
    return console.log(error);
  };

  HOUR_R = /(\d+)h$/;

  YEN_R = /¥(\d+)$/u;

  DOLLAR_R = /\u0024(\d+)$/u;

  get_num = function(regex, target) {
    var ret;
    ret = regex.exec(target);
    if (ret !== null) {
      return parseInt(ret[1]);
    } else {
      return 0;
    }
  };

  transform_card = function(card, total) {
    card.hour = get_num(HOUR_R, card.name);
    card.yen = get_num(YEN_R, card.name);
    card.dollar = get_num(DOLLAR_R, card.name);
    total.hour += card.hour;
    total.yen += card.yen;
    return total.dollar += card.dollar;
  };

  App = (function() {
    function App() {}

    App.prototype.start = function() {
      return Trello.get('/members/me/boards', (function(_this) {
        return function(boards) {
          var _board, i, len, results;
          results = [];
          for (i = 0, len = boards.length; i < len; i++) {
            _board = boards[i];
            if (_board.closed) {
              continue;
            }
            results.push((function() {
              var board;
              board = $.extend({}, _board);
              return Trello.get("/boards/" + board.id + "/lists").then(function(lists) {
                var element;
                element = document.createElement('x-board');
                $('#boards').append(element);
                return riot.mount(element, 'x-board', {
                  board: board,
                  lists: lists,
                  getCards: _this.getCards
                });
              });
            })());
          }
          return results;
        };
      })(this));
    };

    App.prototype.getCards = function(e) {
      var listing;
      listing = e.item.listing;
      return Trello.get("/lists/" + listing.id + "/cards").then(function(cards) {
        var card, element, i, len, total;
        element = document.createElement('x-billing');
        $('#cards').html('');
        $('#cards').append(element);
        total = {
          yen: 0,
          dollar: 0,
          hour: 0
        };
        for (i = 0, len = cards.length; i < len; i++) {
          card = cards[i];
          transform_card(card, total);
        }
        return riot.mount(element, 'x-billing', {
          cards: cards,
          listing: listing,
          total: total
        });
      });
    };

    return App;

  })();

  window.TrelloBilling = App;

}).call(this);
